### ISSUE TITLE
Request for a looper

### ISSUE THREAD

**Issue by Draceno** [tuntorius/mightier_amp#104]
please add a simple looper like TC Electronic Ditto with overdubs, undo and redo functions. Midi/keyboard controllable would be great.

**Comment by amr66** [comment]
I'm not the developer, but because MIDI does not transport sound, I think this is impossible. If the amp had a looper built in, the app could control it through MIDI. Bluetooth would be another option to transport sound, but it's only one way: into the amp. USB would be another choice, if you can register your amp as a sound card on your phone/PC, but the app does not support recording through USB. May be, there are other apps, like the J4T multitrack recorder, which can record audio through USB. (I had no luck so far.)
