### ISSUE TITLE
UI update when using the DLY/RVB knob

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#13]
I read Dian Iliev's post on Facebook, where he mentioned that he added the UI update function without even having an amp for testing. Great effort!

When checking this function I came across two issues:

 1. The UI feedback only seems to work on the first channel. Channels 2 to 7 are unaffected.
 2. It only works for changing the delay mix. When holding down the TAP button to switch to reverb (light of the button changes colour), the reverb level won't change in the app.

Clearly a low priority issue.

**Comment by tuntorius** [comment]
1. I can't find a reason for this behavior. I have a possible theory though. The amps use midi for communication but it's implemented incorrectly. I don't know if you are familiar with it but it allows you to control up to 16 channels. NUX could have used 7 of them to map to the actual 7 channels of amp, but they don't. At least in direction Amp->App they only use midi channel 0 for all communication. Now maybe in the other direction they properly use 7 channels, idk. If that's the case, my app expects everything on channel 0 and that's why it doesn't work.
2. Maybe the send something more specific for that control. All the parameters should have the same message code for both directions but maybe this is an exception.

There's a way to log the messages that the amp sends which will help me alot in order to find what's wrong. Go to Settings, scroll down and tap on App version 7+ times. Then scroll a bit more and you'll see 2 new options. Tap on MIDI Commands Utility. Then when you change something on your amp, the corresponding message will show up.
For example if you change the amp gain, it should be something like this:
176, 13, X - where X from 0 to 127.
If my assumption about the channels is correct, then for channel 2 to 7 the first value won't be 176 but 177, 178 etc...
You can also check what the message is for reverb knob.

**Comment by TullyMore** [comment]
Hi Tuntorious,

thanks for letting me know about the MIDI utility. I have no experience with MIDI, so I used the standard settings in the MIDI console and didn't change any of the available settings.

Here‘s a list of the values for the different knobs. The numbers stay the same, when using different channels:
Gain:      128,128,176,79,X
Volume: 128,128,176,81,X
Tone:     128,128,176,80,X (Jazz Clean)
Reverb: 128,128,176,87,X
Delay:    128,128,176,85,X

I specifically test reverb and delay channels 1, 2 and 7 and the behavior was the same for all of these. Please find the results below.

In general the range lies between 1 and 127 when turning from off to full and 125 to 0 when going from full to off.

However, many times the maxima for full wasn't reached and only did go to e.g. 125 instead of 127. It needed a couple of attempts to go to the full 127. I assume the reason for this could be the controller button on the amp not being overly accurate as you sometime can see jumps between the numbers somewhere else e.g. going from 12 to 14, or 33 to 32.

I also noticed a random message appearing every X seconds in the midi log, which I also included below. Interestingly, the fourth number from last changed during my initial tests, but now I can‘t reproduce this behavior and the number always stays 99.

I found that the tone knob, also isn't supported correctly yet. I will open a separate issue for that.

Please let me know, if you need more information.


Changing reverb from off to full on channel 1:
128,128,176,87,1 to 128,128,176,87,127

Changing reverb from full to off on channel 1:
128,128,176,87,125 to 128,128,176,87,0

Random message: 128,128,240,0,17,34,48,0,112,5,66,96,19,50,67,128,247
Note that the fourth number from last differs to the random message sent by delay.

No midi output when switching between delay and reverb and vice versa by pressing DLY/RVB button on amp. Please note, that second last number in the midi command changes from 87 to 85.

Changing delay from off to full on channel 1:
128,128,176,85,1 to 128,128,176,85,127

Changing delay from full to off on channel 1:
128,128,176,85,124 to 128,128,176,85,0

Random message: 128,128,240,0,17,34,48,0,112,5,66,96,19,8,67,128,247
Note that the fourth number from last differs to the random message sent by reverb.


Changing reverb from off to full on channel 2:
128,128,176,87,1 to 128,128,176,87,127

Changing reverb from full to off on channel 2:
128,128,176,87,125 to 128,128,176,87,0

Random message: 128,128,240,0,17,34,48,0,112,5,66,96,19,95,66,128,247
Note that the fourth number from last differs to the random message sent by delay.

Again no midi output when switching between delay and reverb and vice versa by pressing DLY/RVB button on amp. Again, the second last number in the midi command changes from 87 to 85.

Changing delay from off to full on channel 2:
128,128,176,85,1 to 128,128,176,85,127

Changing delay from full to off on channel 2:
128,128,176,85,124 to 128,128,176,85,0

Random message: 128,128,240,0,17,34,48,0,112,5,66,96,19,95,66,128,247
Note that the fourth number from last differs to the random message sent by reverb.

**Comment by tuntorius** [comment]
Thanks a lot for the extensive testing.
You don't have to change anything on the midi utility screen. This is used if you want to send a message.
Don't worry about values not going fully 0-127. It's normal for those analog potentiometers, they are simply not that accurate.
The recurring message is the battery status. Just ignore it.

Anyway, I found what the problem is. Very silly mistake. It works only on the first item in whatever effect slot it controls. For example it works only on Jazz clean amp, because it's the first one. It's just a coincidence that this amp is setup by default for channel 1 and all the rest of the channels have other amps. Same thing for delay/reverb. It will work only for analog delay/room reverb. You can test it to confirm this but I'm sure that's the problem.

**Comment by TullyMore** [comment]
Happy to help.

Just checked with the first item on the list for amp, delay and reverb on channel 3. Works like a charm. Guess you found the issue. Great job!
