### ISSUE TITLE
maximum level of loudness

### ISSUE THREAD

**Issue by JK5150** [tuntorius/mightier_amp#18]
Hello!
This question mb would be strange)
But
maybe it is real to implement some master tuner, which would increase final loudness to maximum of this device?
Or maybe modify your master tuner which you implemented already - to 200 or 300%?
I'm really using this device for live sessions, and there is an annoying point - this device has too weak output signal
And I think that there is a big reserve of loudness, but some of channels couldn't reach it

suddenly I found that bass presets seems much louder than acoustic simulator channel, and this point give me this idea about increasing of output loudness on a master level
Thanks you in advance!

**Comment by tuntorius** [comment]
Sorry, this is not possible, the volume range is limited by the device. The amp is just a remote control and can't do anything to extend it. The master volume slider I implemented is fake - it simply modifies the amp level internally.
There are people who used my IR replacement tool found out that using some 3rd party IRs increased the volume. The tool Is here:
https://github.com/tuntorius/nux-ir-patcher
But even this way I doubt you'll get more than 20-30% of additional gain.

Also I'm sure that even if 200-300% gain is somehow possible, it would wreck the sound. The additional gain should come from an external power amplifier.

Which amp do you have? If you have Mighty Plug then the only option is an external amp since the output is suitable for headphones only. It cannot power speakers. I'm not familiar with Mighty Air or the other amps with speakers but I think their speakers are not very loud and you still might want to use the headphone out with an additional amplifier.

**Comment by JK5150** [comment]
Hi! I just mean - for example, we have maximum loudness of device in one of bass channel - for example 100 cents.
And acoustic guitar amp channel maximum loudness is only about 30 cents - if compare with bass amp above.
And I mean - acoustic amp is drives only 30% of maximum of device, and if we boost it somehow in software - it wouldn't distort final sound - this is only my idea. But sure, maybe I'm not right :) 

I talk about mighty plug

Omg, custom IR? AMAZING, I need to test it 😱😱😱

**Comment by tuntorius** [comment]
OK I understand, you mean the gain variances between different amp types. I totally agree, there is a big difference between clean and distorted amps for example. That may be due to the way they implemented the software simulation of the amps or it could be due to the corresponding IRs having low amplitude.
This is the waveform of the internal IRs:
https://drive.google.com/file/d/1WLxFeQge_UI8TxONgHB0JoL23RR8kL7c/view?usp=sharing
Ignore that they are reversed, this is how they are stored inside the firmware. Notice that the acoustic IRs have a very high amplitude compared to the others. That's why they sound way louder. If you can find such IRs for other cabinet types and patch them into the firmware, the gain will probably increase.

**Comment by JK5150** [comment]
Thanks you, it's good idea!
