### ISSUE TITLE
Inclusion into F-Droid

### ISSUE THREAD

**Issue by ashimokawa** [tuntorius/mightier_amp#21]
Hi, 

I just wanted to let you know, that I am working on including your app into [F-Droid](https://f-droid.org).

I do not use Google Play and I was happy to find something that I can compile myself :+1: :smiley: 

To make your app comply to F-Droids standards and to make it compile I did the following modifications, see [MR on GitLab](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10056):

* Removed tuner (needs included jar of unknown origin, against F-Droid rules)
* Removed YouTube (did not build)
* Sentry (analytics, did not build)

I also included your donations link into the app metadata, which will become clickable right from the F-Droid app and the F-Droid website.

As a side note, if you support the inclusion into F-Droid and want to make the F-Droid release a build flavor, you are even allowed (in contrast to Google Play) to add a donation link right into the app for that build flavor.

**Comment by tuntorius** [comment]
Hi, 

thanks for the interest in my app. I'm glad you like it and I don't mind its inclusion into F-Droid.

Btw you probably didn't pull the latest changes because Youtube should compile. It's currently shown in debug mode only because I believe it violates Google terms - it directly gets the audio URL which means no ads, ability to play in the background, etc. but it may be ok for F-Droid. It needs more work though.

I am going to remove the tuner myself because it doesn't detect notes that well.

**Comment by ashimokawa** [comment]
@tuntorius 

Thank you for the positive reply :) 

It is true that I did not try to build the latest changes, because F-Droid normally only builds tagged releases.

Before inclusion I will propose a PR which will add fastlane metadata, which will then be used for the F-Droid description automatically. It is not a hard requirement but somehow expected by F-Droid.

**Comment by ashimokawa** [comment]
@tuntorius 

Did a PR for fastlane.

YouTube *could* actually be enabled for the F-Droid builds, because it is not against F-Droid terms, however it would then display an "anti-feature" because Mightier Amp would then "promote" non-free services (YouTube).

For me either is fine.
It would also be possible to create build flavor for F-Droid which would then include YouTube and a donation link inside the app (both not allowed by google, but allowed by F-Droid)

Anyway, first step is to get this included. :)

**Comment by tuntorius** [comment]
Accepted the PR.

It turns out Flutter can only detect which flavor is running at runtime and execute different code paths based on that. It can't disable dependencies at build-time. This means that even if I avoid using a certain library at runtime, it still has to be included in the build. That's a problem with libs that are against F-Droid rules. I guess that includes everything Google-based.

At some point, I'd like to allow the users to store their presets in a cloud-based service. That will require authentication. I'm going to use several methods and google account auth is going to be one of them, because it's the easiest for people with google enabled devices. This might be a problem for F-Droid.

**Comment by ashimokawa** [comment]
@tuntorius 

Not everything is against F-Droid rules, if it is I can patch it out.

I saw some flutter apps on F-Droid which build a flavor, no sure how they did it

**Comment by ashimokawa** [comment]
Is is included now, closing this. :rocket: :guitar: 

https://f-droid.org/en/packages/com.tuntori.mightieramp/
