### ISSUE TITLE
Feature Request: Bypass Amp and Cab/IR. 

### ISSUE THREAD

**Issue by zekebeckman** [tuntorius/mightier_amp#30]
Hi!
Would it be possible to add a feature where you can bypass every block individually? So that you can use only the amp, the IR or reverb ETC.
That would be remarkable!

**Comment by tuntorius** [comment]
Hi, unfortunately, that's not possible to do from the app. It is merely a remote control and can only do stuff with a bunch of control commands that the amps already support. NUX will have to implement it inside the device firmware.
I have a list of all the control commands for the NUX amps and interestingly enough there's an on/off command for each block, including the amp and the IR block but these two don't do anything. I have tried it many times with all available firmware versions to see whether it works but it doesn't. I believe these exist simply because the amp has a standard set of commands for each block but simply ignores these.

Still, you can achieve bypassing of the IR block by patching in a null IR using my IR tool. However most null IRs you can find online don't work with Mighty Plug for some reason - there's no audio output. There is a working null IR in this dropbox folder made by by Alex Kenivel:
https://www.dropbox.com/sh/85qd369nnqc5y7c/AADqtFMjj7gEeiKbIhAKAA5da?dl=0&fbclid=IwAR3gJEpOruzquPwHG9ZZ37-1gMX7DZ0XLEy0QIExKnSoIYlUgSdkHvxWsCY
The IR patching tool is here:
https://github.com/tuntorius/nux-ir-patcher

**Comment by zekebeckman** [comment]
Huge thanks for the articulate reply, and for the tips!

**Comment by AlessandroChecco** [comment]
What would be the most neutral sounding amp/settings? I guess a clean one or an acoustic one?
