### ISSUE TITLE
Connection crushes while track events adding

### ISSUE THREAD

**Issue by JK5150** [tuntorius/mightier_amp#31]
Hello! As I could see - you did AWESOME feature - adding events with preset changing for tracks
Thats really mindblowing awesome 😊but while I make some taps between added events - bluetooth connection with device crushes - and nothing could help - only reboot of device :(

**Comment by tuntorius** [comment]
Hi,
the same thing happens to my device, but not only with Mightier Amp. It's true that it happens more often when adding events and a track is playing, but it also happens when for example youtube is playing and I'm adjusting parameters using the official app. In that case, my app is not even launched. 
I noticed that in order to trigger the bug, I have to adjust multiple things quickly in succession. That is why it usually goes unnoticed by most people, because no one uses it like that, especially when a backing track is playing.
Unfortunately, that "vigorous" changing of effect parameters is essential for the jam track module. It must change all the parameters to those of the next preset as quickly as possible.
