### ISSUE TITLE
App working with Mighty 8BT with a minor inconvenience

### ISSUE THREAD

**Issue by fumil** [tuntorius/mightier_amp#34]
Hi Tuntorius,

I confirm that your great app is working flawless with Mighty 8BT. I'm using a Huawei phone with HarmonyOS v 2.0
Still, there is a minor issue - I don't know if actually that can be considered a bug:
When playing a jam track, there is no way to adjust amp settings "on the fly" as the track is paused when leaving player's screen. It would be great to get that fixed in the next release.

Thanks so much for your great work!

**Comment by tuntorius** [comment]
HI,

I know this is inconvenient and I'm going to improve it but for now, the jam track module is at a low priority.
If you are using the module to its full potential, you can add automatic preset changes along the runtime of the backing track. If the track contains such points and at the same time you try to adjust the amp settings, it's highly likely that you will "fight" with those automatic changes. Back when I worked on this module, the simplest "fix" for this was to stop the song when you leave the jam track page.
I know it is possible that your backing tracks have no such points at all, in which case manually adjusting the amp parameters is valid.
My plan to fix this is to allow the track to play everywhere and make the app check if there are such preset change points in it. If there are - the effect controls will be greyed out with an explanation of why. Otherwise, the controls will stay enabled.
