### ISSUE TITLE
Master Volume output

### ISSUE THREAD

**Issue by SMcbrain** [tuntorius/mightier_amp#38]
First of all congratulations for the killer app. Using the Mighty Plug, when listening to a backing track via the JamTracks tab, it is necessary to stop playback in order to adjust the guitar's master volume. Would it be possible to configure the volume to be adjusted while playing the backing track? Thank you!

**Comment by tuntorius** [comment]
My plan is to make Jam Tracks available everywhere in the app so you can get out of the setlist and adjust whatever you want. This will introduce a problem though - if the jam track has points with patch changes, the effect editor tab will have to be locked for editing while the track is playing. Otherwise, the user and the jam track events may "fight" over the parameter changes. Of course, if the track has no such events, everything will be unlocked.
