### ISSUE TITLE
Feature request: Circumvent location setting

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#52]
Hi,

I am aware, that this is a Android issue. But is there any chance, to trick Bluetooth to believe,  that location setting is activated? I usually have location switched off to preserve battery and it’s quite inconvenient to always have to switch it on and remember to switch it off again.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted

**Comment by tuntorius** [comment]
This is possible only on Android 12+, and I tried to implement it. However, I have only an Android 11 phone so I don't know if it works.
In those Android versions there are 2 new Bluetooth permissions - scan and connect. Mightier Amp should ask for those, instead of the location one. And should work with the location setting off.

**Comment by TullyMore** [comment]
Hi,

just did a test with v0.9.8 on Android 13 on Samsung Galaxy A52s 5G and it appears to be working. Great Job!

regards
