### ISSUE TITLE
Feature request: Display of current preset name

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#53]
Hi,

it would be nice, if the current preset name could be displayed on the main screen, as you can’t see, which preset currently is saved to a channel.

A plus would be, if the preset name could be preselected, when saving the preset, after making changes to it. Currently this only works, when selecting the preset in the preset tab first, but not, when selecting a channel and then saving the preset.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted

**Comment by tuntorius** [comment]
Added in 0.9.8

**Comment by TullyMore** [comment]
Hi,

thanks for your ongoing efforts. Will check on issues #53, #54 and # 55 when I find the time. Great job as always!

Regards
TullyMore

**Comment by TullyMore** [comment]
Hi,

the current preset name is shown now, which is really nice. Unfortunately it's not visible in landscape mode as the row with the bluetooth sign isn't shown.

Regards
TullyMore

**Comment by tuntorius** [comment]
On many devices the controls in landscape mode are very squished even without the bar on top. That's why the bar is integrated into the side bar.
![Screenshot_20230302-182008](https://user-images.githubusercontent.com/74666721/222489078-639d7706-4644-426a-ad19-206775cc524f.png)
Just use the arrow to expand it.

**Comment by tuntorius** [comment]
I had the chance to test the app with a few tablets and it turns out that on some of them, the app switches to some kind of portrait mode, even though they are in landscape mode. However, the app bar is missing in this 3rd mode. I think this happens only on very high-density screens, and there's more than enough space for the app bar. I'll look into adding it for this mode.

Just to confirm it's the same thing. When you say you don't have the app bar, is the app looking the same as in portrait mode - with the tabs on the bottom, or is it looking like the screenshot from my previous post - with a sidebar?

**Comment by TullyMore** [comment]
Hi,

it's looking like in you screenshot on all of my devices.

Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Android 7.1.2 on Nexus 7
Mightier Amp v0.9.6

**Comment by tuntorius** [comment]
The new version will display the full title bar and tabs on the bottom in landscape mode if there's enough screen space to fit everything vertically. This should be the case for most tablets. Phones will use the interface from the screenshot above.

**Comment by TullyMore** [comment]
Hi,

works great and looking good on my Tablet. Great job!

regards
TullyMore

**Comment by TullyMore** [comment]
Hi,

enjoying my holidays and spending my time with the Mighty Air. 

Showing the preset works fine, when the preset is selected from the editor tab. Alas, when you select any of the stored presets on channels 1 to 7, the name isn't shown. Any chance to fix that?

regards
TullyMore

**Comment by TullyMore** [comment]
Hi,

could I ask again for implementing the feature I mentioned in my last comment?

It would be nice to see the name of the current preset, that is stored on a channel. Currently it's only shown, when loading a preset via the presets tab. Ideally this would also work, when selecting a channel using the channel button on the Mighty Air.

As a plus, the current preset then would be pre-selected when saving it, after making changes to it.

regards
TullyMore
