### ISSUE TITLE
Issue: Colours of channel button not matching

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#54]
Hi,

another minor issue. The colours on the channel buttons 2, 4, 5 and 6 aren’t matching the displayed channel colours in the Mightier Amp app.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted

**Comment by tuntorius** [comment]
Fixed in latest 0.9.8 release.

**Comment by TullyMore** [comment]
Hi,

thanks for fixing this. Colours for channel 2 and 4 are now matching. Buttons 4 and 6 unfortunately still aren't correct.

Regards
TullyMore

**Comment by tuntorius** [comment]
I see. You are talking about the channel buttons on the editor page. I haven't changed the colors of the channels on that page at all, there's no way I "fixed" colors 2 and 4.
To me, they look good enough - both Mighty Plug and Mighty Plug Pro. Maybe not perfect, but I made sure it's recognizable which channel are you on. Then I adjusted some a little so that the white text on the amp sliders is readable (this is for MP-2). There may be a variance between devices. If I judge by the official app, its colors are way off, compared to what my Mighty Plug MP2 shows. What do you see? Is it like a red vs blue difference?

There was a bug in the presets tab, however. Mighty plug pro presets were showing the colors of Mighty plug MP-2 presets. I thought you were talking about that. This is the thing I fixed.

**Comment by TullyMore** [comment]
Hi,

I'm using a Mighty Air. Maybe, that's the reason for the different colors.

Button 4 on the Amp is purple. In the App it's gray with a blueish hint.
Button 5 on the Amp ist green, but not as strong as button 1 green. In the App it's light blue.
Button 6 on the Amp is orange. In the App it's purple.

Please find pictures attached.
![Amp_Button4](https://user-images.githubusercontent.com/23203432/223698120-29ebb629-0d06-490e-8844-9ddeb52c1c5b.jpg)
![Amp_Button5](https://user-images.githubusercontent.com/23203432/223698193-5e3a49b9-eacd-4fbb-ba86-a86062b97b38.jpg)
![Amp_Button6](https://user-images.githubusercontent.com/23203432/223698215-dbf7b16a-d6b1-4938-93dc-40858b044723.jpg)
![App_Button4](https://user-images.githubusercontent.com/23203432/223698230-13c3d205-4b35-4599-897a-aa52a23e0c59.jpg)
![App_Button5](https://user-images.githubusercontent.com/23203432/223698247-1171078c-07b4-4b29-982a-8a7b7c3cef40.jpg)
![App_Button6](https://user-images.githubusercontent.com/23203432/223698257-834f9ded-4130-455d-86bb-502fabd216fb.jpg)

**Comment by tuntorius** [comment]
You're right, they have different colors. I always assumed that Air and Plug were identical and I didn't pay attention to details. I'll copy the colors from the official app.
