### ISSUE TITLE
JamTracks no access to Media Library

### ISSUE THREAD

**Issue by tgeysen78** [tuntorius/mightier_amp#59]
V0.9.8 jamTracks shows button 'grant access to Media Library' but pressing this button does nothing? Android 13 Realme UI 4.0. Using Mighty Plug Pro.  thanks

**Comment by tuntorius** [comment]
Hi, thanks for reporting this. Go to apps permission settings in android settings menu and grant the media permission to Mightier Amp manually.
The button works only the first time, but if you pressed "deny" on the popup that followed, it won't work anymore.
I'll replace the button with a proper description for such a case.

**Comment by tgeysen78** [comment]
Hi, thanks for the reply. Unfortunately, I don't have the possibility to set these media permissions via app settings. I only have location and nearby devices & camera. I have uninstalled & reinstalled with no luck. I tried installing on another phone , but this time running Android 12, and here it worked as expected. So could it be android 13 related?

**Comment by tuntorius** [comment]
Yes, it's an Android 13 problem, but it is strange that in your case it was showing the permission button instead of the JamTracks window. That's why I thought you had the permission permanently denied. Other android 13 users told me they see the jam tracks, and can even add tracks, but they don't play and show a duration of 00:00.
Android 13 removed the external storage permission entirely. Now it has specific permissions for audio, video, and images. So I have to request the audio one instead. I'll publish an update very soon.

**Comment by tuntorius** [comment]
Fixed in version 0.9.10
