### ISSUE TITLE
Unable to connect to NUX MP-2

### ISSUE THREAD

**Issue by itm1960** [tuntorius/mightier_amp#75]
I've installed Mightier Amp on a Moto G 5G Plus. I can see my NUX MP-2 when I click the Scan button, but when I try to connect to it I always get a "Connection Failed" error. The stock MightyAmp app connects to it without any problems.
Any ideas??

**Comment by tuntorius** [comment]
Sorry for answering so late. If you still have that problem, can you check if there are any errors in the app log? You can do it by going to the settings tab and tapping 7 times on the app version. Then you can scroll further and you'll find some new options including a debug console. Now try to connect your amp and then open the debug console. You can post the log here and that will help me find what the problem is.

**Comment by tuntorius** [comment]
How old is the version of Mightier Amp that you use? This log is from a version that does not support MP-2 firmware 2.x. I added that support more than 2 years ago.

**Comment by itm1960** [comment]
Ah OK I was running 0.8.2. I've just done a fresh install from the Play
Store and it has resolved the issue.
Many thanks!

**Comment by tulipanaccio** [comment]
Hello,
I have a similar issue, but with a Mighty Plug Pro and with version of Mightier Amp 1.0.12 on a Motorola Edge 20 Lite. Interesting the App installed through Google Store doesn't request me authorization for GPS position. I'm attaching the log of the failed connection. Thanks in advance for the support.
[mightier_amp_log.txt](https://github.com/tuntorius/mightier_amp/files/14910356/mightier_amp_log.txt)
