### ISSUE TITLE
Nux Mighty Lite BT ambience doesn't work

### ISSUE THREAD

**Issue by tade90** [tuntorius/mightier_amp#77]
When I connect my Nux Mighty Lite BT to the app, the other tabs work fine until I select the ambience tab, it got greyed out and sometimes I can't even switch to other tabs. Is there anywat to fix this in the future? I'm using IOS,  app version 1.0.6

![368557489_628844962780368_4317951220344852918_n](https://github.com/tuntorius/mightier_amp/assets/90448177/6aebb54b-cd44-49ec-9a63-ac43bd7a1d74)

**Comment by amr66** [comment]
Same as #74, I think. A solution would be great!

**Comment by tuntorius** [comment]
Unfortunately, I don't have the Mighty Lite BT and can't reproduce it.
Does it happen with a specific preset from the library?
Does it happen only when the amp is connected?
If this happens to a certain preset even when the amp is not connected, please send me the preset file. Not a QR code, but an actual export from the presets that produces a *.nuxpreset file.
This or similar bug was present in one of the previous versions and was easy to reproduce even without the amp. I fixed it but maybe this is another, similar case that happens rarely or only with an actual amp connected.

**Comment by amr66** [comment]
I can confirm for my android smartphone that it only happens when the amp is connected.

**Comment by tade90** [comment]
I got my Nux BT connected properly, every function works fine EXCEPT for Ambience setting. Before it got connected i can actually access the ambience tab and it looked normal, the bug happens AFTER it got connected. Here is the picture before the connection with the amp. 
![image](https://github.com/tuntorius/mightier_amp/assets/90448177/66498c44-50ab-4c18-95d3-edeb5dcfff40)

**Comment by amr66** [comment]
Looks the same, here. @tuntorius, may be there is a chance to filter out the MIDI messages when using the original app? Like a "man in the middle"? Do you know what I would need?

**Comment by tuntorius** [comment]
I think I found the bug - an incorrect CC message for the selected ambiance effect.
Here is a test apk for Android:
https://drive.google.com/file/d/1UB9LdTwrad6-NqWKnDD5tjn7QlQPtn9j/view
It installs as a separate app so it won't mess with the original app you have.
I can't give you a test version for iOS, but when this bug is resolved, I'll publish an update.

**Comment by amr66** [comment]
Thanks for your efforts!
I just tested your APK, and after connecting the amp I can switch between Gate, Amp and Mod but Ambient fails. Screen shows an error now: On red background, I get

````
RangeError(index) Invalid value: Not in inclusive range 0..7: 13
See also: https://flutter.dev/docs/testing/errors
````

**Comment by tuntorius** [comment]
It's getting closer. There's a gap in the numbering of the ambiance effects - the delays are from 0 to 3, but the reverbs are from 10 to 13. I didn't account for that because all the other NUX amps have contiguous numbering.
Try with this build:
https://drive.google.com/file/d/1BSXUvLEPLTq5GcT3d3YgaMuFEAfM30kN/view?usp=sharing

**Comment by amr66** [comment]
You got it! I see the ambient screen now and can switch the effects and trim the parameters! 
Thank you very much!
